[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  REACT_APP_API_URL = "https://api.production.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 